### ISSUE TITLE
Add definitions or links to additional terms

### ISSUE THREAD

**Issue by DougHockin** [v-nys/programming-emu#14]
On this page:

[http://users.telenet.be/vincent-nys/parenlog/introduction.html]

Consider adding a definition, or a link to one, for “S-expression” and "DSL".

Your might have readers who don’t know what they are.

Aside: The writing and explanations are really good. Thanks for writing this.

**Comment by v-nys** [comment]
Hi Doug, it means a lot that you are enjoying the book and I appreciate the suggestion. I've started a feature branch for a glossary.

**Comment by v-nys** [comment]
Hi Doug,

I've added a glossary to the version that's currently online.
